### PR TITLE
Etcd Updates

### PR DESCRIPTION
**Pull request by askmike1**
# Description

Resolves compatibility issues with Etcd 3.5.0+ and Chef

## Issues Resolved

https://github.com/sous-chefs/etcd/issues/120
https://github.com/sous-chefs/etcd/issues/122

## Check List

- [x] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by ramereth** [comment]
I really feel like this doesn't solve the problem in the long run. We need to fix the code so that it does work with `unified_mode true`. Can you please look into fixing that instead of just disabling it?

**Comment by askmike1** [comment]
I am not the owner of this cookbook, my goal is to simply get it in a working state that is compatible with the latest version of chef & etcd. I'd welcome any different updates though that writes the code in a more ideal manner.

**Comment by damacus** [comment]
Thanks for the PR @askmike1 we appreciate all PRs. Even if, as is the case is here, it's not the solution we're looking for as a community. 

This highlights our lack of guidance on sous-chefs.org. We should really be clear about `unified_mode true` not being optional now. As `unified_mode` will be on by default in Chef 18.

**Comment by damacus** [comment]
That said, I think we should accept this PR *as is* but look to fix whatever is stopping unified mode from being enabled and working.

**Review by damacus — APPROVED** [review]
Approved based on us fixing Unified Mode in the future.

**Pull request merged**
